// Loading
export const LOADING = 'LOADING';
export const NOT_LOADING = 'NOT_LOADING';

// Manage Errors
export const LOG_ERROR = 'LOG_ERROR';

export const FETCH_COMPANIES = 'FETCH_COMPANIES';

export const FETCH_COMPANY_CATEGORIES = 'FETCH_COMPANY_CATEGORIES';

export const FETCH_COMPANY_OFFENCES = 'FETCH_COMPANY_OFFENCES';

export const SET_AUTHED_USER = 'SET_AUTHED_USER';

export const LOGOUT_USER = 'LOGOUT_USER';

export const RECORD_COMPANY = 'RECORD_COMPANY';

export const SEARCH_DRIVER = 'SEARCH_DRIVER';
