// Loading
export const LOADING = 'LOADING';
export const NOT_LOADING = 'NOT_LOADING';

// Manage Errors
export const LOG_ERROR = 'LOG_ERROR';

export const FETCH_COMPANIES = 'FETCH_COMPANIES';

export const FETCH_COMPANIES_WITH_DETAILS = 'FETCH_COMPANIES_WITH_DETAILS';

export const FETCH_COMPANY_CATEGORIES = 'FETCH_COMPANY_CATEGORIES';

export const FETCH_COMPANY_OFFENCES = 'FETCH_COMPANY_OFFENCES';

export const SET_AUTHED_USER = 'SET_AUTHED_USER';

export const LOGOUT_USER = 'LOGOUT_USER';

export const RECORD_COMPANY = 'RECORD_COMPANY';

export const SEARCH_DRIVER = 'SEARCH_DRIVER';

export const FETCH_DOCUMENTS = 'FETCH_DOCUMENTS';

export const RECORD_DRIVER = 'RECORD_DRIVER';

export const FETCH_DRIVER_OFFENCES = 'FETCH_DRIVER_OFFENCES';

export const FETCH_DRIVER_INVOICES = 'FETCH_DRIVER_INVOICES';

export const FETCH_MY_INVOICES = 'FETCH_MY_INVOICES';
